# Generated by Django 5.1.5 on 2025-01-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('artículo', 'Artículo'), ('video', 'Video'), ('podcast', 'Podcast')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('enlace', models.URLField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.categoria')),
            ],
        ),
    ]
