# Generated by Django 5.1.5 on 2025-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], default='cliente', max_length=50),
        ),
    ]
