# Generated by Django 5.1.5 on 2025-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('psicologo', 'Psicólogo'), ('cliente', 'Cliente'), ('admin', 'Administrador')], default='admin', max_length=50),
        ),
    ]
